package com.serverweb.web;

public enum StatusCode {

    CLIENT_ERROR_400_BAD_REQUEST(400, "BAD REQUEST DETECTED"),
    CLIENT_ERROR_401_METHOD_NOT_ALLOWED(401, "THIS METHOD IS NOT ALLOWED "),
    CLIENT_ERROR_414_ARRAY_OVERFLOW(414, "DETECTED URL IS TO LONG"),
    SERVER_ERROR_500_INTERNAL_SERVER_ERROR(500, " INTERNAL SERVER ERROR DETECTED"),
    SERVER_ERROR_501_METHOD_NOT_IMPLEMENTED(501, "NOT IMPLEMENTED"),
    ;

    public final int  STATUS_CODE;
    public final String  MESSAGE;

    StatusCode(int STATUS_CODE, String MESSAGE) {
        this.STATUS_CODE = STATUS_CODE;
        this.MESSAGE = MESSAGE;
    }



}
